Development
Gunjuzone/My_Portfolio pull request #1
Opened 2021-06-04 15:47 UTC by Gunjuzone

2021-06-04 18:57 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @Gunjuzone  ! :wave: :wave:

#### You have done really well in implementing the requirements.
- You used proper GitHub Flow ✔️ 
- Your linter checks are all passing ✔️ 
- You have shown a good understanding of Flexbox ✔️ 
- Your PR message is descriptive ✔️ 

 However, there are changes required for you to make in order for this project to be approved.
 

>  Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. :smile:

 
- - -

### **Recommended** ♻️
- [ ] Your Readme is not showing up because you have placed it inside the `First_Page` folder. It should be in the root folder along with the linters as well.
- [ ] I can see what you were trying to do in organising your files. However, files like the linter files. .`.gitignore` , `README.md` should all be placed in the root directory. You can create an `assets` folder for your stylesheets and images. Kindly restructure your directory to reflect these changes.

_See the inline comments below for more required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- Consider using[ Font Awesome](https://fontawesome.com/v4.7/icons/) icons for your project instead of images.

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have 2 more reviews as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

2021-06-04 18:57 UTC, Temmarie commented on First_Page/Portfolio.html
> +        </nav>
- [ ] The container of the section should be a `header` tag. Wrap the `nav` tag in a `header` tag. 
- [ ] Since you're using plain text for the logo, it should use a heading tag `hx` and should have a link (`a` tag).

Headers tags indicate headings on a webpage by using code to tell a web browser how to display content. That's why and how they organize your content into a format that's easy to read. In addition to general structure and readability, heading tags help improve accessibility for people who can't easily read screens.

- [ ] You must stick to the design as much as possible (e.g. font, colors, images, tests, margins) using the [templates in Figma.](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). 
- The toolbar/navigation bar has a smaller height/width compared to the design in the template.
- The logo and the menubar should be horizontal aligned.


**Original** | **Your clone**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/120846117-8a05d800-c526-11eb-806b-7b5ea95f66f2.png) | ![image](https://user-images.githubusercontent.com/49621279/120846180-9be77b00-c526-11eb-9fb9-3c636620a980.png)

2021-06-04 18:57 UTC, Temmarie commented on First_Page/Portfolio.html
> +        </main>
- [ ] The container of the section is a `section` tag. Using a `section` tag to group the headline and social media links orders the element semantically making it obvious to screen readers or assistive technologies to know they belong to the same group.

2021-06-04 18:57 UTC, Temmarie commented on First_Page/Portfolio.html
> +                    <img src="Images/Group.png" alt="" class="banner_img">
- [ ] The section has the proper background image (decorations are always background images, not `img` tags).
- [ ] Align the background image to be as similar as possible to the design template you are following.

_See my comments about design above._

**Original** | **Your clone**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/120848310-8162d100-c529-11eb-92c2-2dac18249a6e.png) | ![image](https://user-images.githubusercontent.com/49621279/120848515-bcfd9b00-c529-11eb-84fc-846bf92e0632.png)

2021-06-04 18:57 UTC, Temmarie commented on First_Page/Portfolio.html
> +                    <p class="sub">I am a Software Developer</p>
- [ ] The subtitle should use a header tag `hx`. Heading tags indicate headings on a webpage by using code to tell a web browser how to display content. They also help improve accessibility for people who can't easily read screens.
See [here](https://www.w3schools.com/html/html_headings.asp) for more info.

2021-06-04 18:57 UTC, Temmarie commented on First_Page/README.md
> +- CSS
- [ ] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
A good README should have a description that is clear, short, and to the point. It should describe the importance of your project, what it does and how to use it. This way technical and non-technical users can understand how to use it.  Refer to this template [here](https://github.com/microverseinc/readme-template) and customise it to your needs.

- [ ] [OPTIONAL] I suggest you take a look at [this](https://www.markdownguide.org/cheat-sheet/) article/cheatsheet that shows how Markdowns work to help improve the clarity of your README.

2021-06-05 09:50 UTC, DeliceLydia commented on First_Page/Portfolio.html
> +        </nav>
You did a good job of implementing some of the changes requested by the previous reviewer but there is one point you need to address so that you can move on

- [ ] Since you're using plain text for the logo, it should use a heading tag hx and should have a link (a tag). please fix that

2021-06-05 09:52 UTC, DeliceLydia commented on First_Page/Portfolio.html
> +        </main>
- [ ] In your code you still have a `div` tag kindly use `section` tag

2021-06-05 09:55 UTC, DeliceLydia commented on First_Page/Portfolio.html
> +                    <img src="Images/Group.png" alt="" class="banner_img">
You really tried to make it similar to the design✔️

2021-06-05 09:58 UTC, DeliceLydia commented on First_Page/README.md
> +- CSS
- [ ] README still doesn't have a description kindly add it, it can be short and clear so that anyone who visits your repo understands what the project is all about even if he is a non-technical person

2021-06-05 10:01 UTC, DeliceLydia requested changes
## Hello @Gunjuzone, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments I added under the previous review._


### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left please work accordingly. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 11:07 UTC, ZawadiSumba66 approved these changes
### Hi @Gunjuzone  👋, 
## STATUS: APPROVED!!! 🎉 🎉 
Congratulations. You have done an incredible job on your project and you are ready to go to the next step. Good luck and all the best!! 👍 👍 

 ## Optional suggestions 
- [ ] Please make sure you follow the advice given by the previous reviewers. The headline should be wrapped in a `section` tag instead of the `main`  tag. This will help to structure your page very well.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 13:26 UTC, merged